# Homebrew owns conventional command-line tools and macOS applications.
# Agent CLIs and language runtimes with supported self-update flows are installed
# by scripts/agents.sh instead.

tap "docker/tap", trusted: { cask: "sbx" }

brew "curl"
brew "direnv"
brew "dockutil"
brew "fastfetch"
brew "fd"
brew "ffmpeg"
brew "gh"
brew "git"
brew "git-delta"
brew "glow"
brew "herdr"
brew "htop"
brew "jq"
brew "less"
brew "pam-reattach"
brew "powerlevel10k"
brew "ripgrep"
brew "stow"
brew "tree"
brew "vim"
brew "wget"
brew "yt-dlp"
brew "zoxide"
brew "zsh-syntax-highlighting"

cask "1password"
cask "1password-cli"
cask "balenaetcher"
cask "chatgpt"
cask "choosy"
cask "cursor"
cask "discord"
cask "docker/tap/sbx"
cask "font-intone-mono-nerd-font"
cask "ghostty"
cask "google-chrome"
cask "handy"
cask "iina"
cask "nvidia-geforce-now"
cask "obsidian"
cask "orbstack"
cask "postgres-app"
cask "raycast"
cask "rectangle-pro"
cask "screenflow"
cask "setapp"
cask "slack"
cask "spotify"
cask "steam"
cask "tailscale-app"
cask "zoom"
